baseURL = "https://hotcheeto.com/"
languageCode = "en-us"
title = "/cheetos"
theme = "hugo-plain-minimal"



[params]
  
  [[params.gallery]]
    image = "/images/photo1.jpg"
    message = "me"

  [[params.gallery]]
    image = "/images/photo.jpg"
    message = "my sunðŸŒž"

  [[params.gallery]]
    image = "/images/photo2.jpg"
    message = "ðŸšµ"
 

[menu]

  [[menu.main]]
    name = "Intro"
    url = "/intro/"
    weight = 1

  [[menu.main]]
    name = "why"
    url = "/why/"
    weight = 2

  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 3

