backend:
  name: git-gateway
  branch: main
  identity_url: https://monumental-sunflower-ad2948.netlify.app
  gateway_url: https://monumental-sunflower-ad2948.netlify.app/.netlify/git


publish_mode: editorial_workflow

media_folder: static/images
public_folder: /images


collections:
  # =====================
  # BLOG POSTS
  # =====================
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Weight", name: "weight", widget: "number", default: 1 }
      - { label: "Content", name: "body", widget: "markdown" }

  # =====================
  # SIMPLE PAGES
  # =====================
  - name: "pages"
    label: "Pages"
    files:
      - label: "Intro Page"
        name: "intro"
        file: "content/intro.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Content", name: "body", widget: "markdown" }

      - label: "Why Page"
        name: "why"
        file: "content/why.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Content", name: "body", widget: "markdown" }
